services:
  - type: web
    name: morm-ecommerce-backend
    env: node
    rootDir: apps/server
    buildCommand: pnpm install && pnpm run build
    startCommand: node dist/main.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://mostafaradwanyos_db_user:Fom1eaQ4DOpTpcK0@users.i5o1asj.mongodb.net/ecommerce?appName=Users
      - key: JWT_SECRET
        value: my-super-secret-jwt-key-2024
      - key: JWT_ACCESS_SECRET
        value: my-access-secret-key-2024
      - key: JWT_REFRESH_SECRET
        value: my-refresh-secret-key-2024
      - key: ALLOWED_ORIGINS
        value: https://morm-ecommerce.vercel.app
